### ISSUE TITLE
Run migration within transaction?

### ISSUE THREAD

**Issue by 3noch** [MichaelXavier/drifter-postgresql#1]
I don't see any use of transactions in the source or the examples, yet Postgres is famous for its ability to do schema changes from within a transaction. Is this intentional? If so, I think it might be wise to use a transaction in the example and mention it in the docs. Or perhaps I've missed something.

**Comment by MichaelXavier** [comment]
I think it was probably an oversight but in hindsight I think we'd want to preserve the ability to not run in a transaction. One example is if you create indices concurrently, those cannot be run in a transaction.

What we have now is:

``` haskell
data instance Method PGMigration = MigrationQuery Query
                                 -- ^ Run a query against the database
                                 | MigrationCode (Connection -> IO (Either String ()))
                                 -- ^ Run any arbitrary IO code
```

And I was thinking I could do:

``` haskell
data instance Method PGMigration = MigrationQuery Query
                                 -- ^ Run a query against the database
                                 | MigrationQueryTransaction Query
                                 | MigrationCode (Connection -> IO (Either String ()))
```

Under most circumstances you'd use `MigrationQueryTransaction` but you could always use the other two escape hatches if you needed to. What do you think, @3noch?

**Comment by MichaelXavier** [comment]
For comparison:

https://github.com/MichaelXavier/drifter-postgresql/compare/transaction?expand=1

**Comment by 3noch** [comment]
Hm interesting take. That's actually not what I had in mind, but it might _also_ be useful. I was imaging running the _entire_ migration process in a transaction. That way, if it fails, you don't end up half-way through your migration procedure. This is easy enough to do by just doing `runMigration` inside of `withTransaction`, but I didn't see any mention of it even though I think it would definitely be the preferred way of running your migrations.

However, I can definitely see some value as well to running _each change_ in a transaction, especially if it were a nested transaction. However, if running each change in its own transaction precluded us from doing the whole suite in a transaction, we would want to prefer the latter.

If we can pull off doing nested transactions (which is a bit trickier in postgres), then perhaps we could just introduce a combinator `inTransaction :: Query -> MigrationQuery` where it just uses the `MigrationCode` constructor and wraps the query with `withTransaction`.

``` haskell
inTransaction query = MigrationCode $ \conn -> withNestableTransactionThing conn (execute query)
```

**Comment by MichaelXavier** [comment]
Ah I see. I guess the problem with running the entire migration in a transaction is that you don't know til runtime (and drifter will never know) if there are any migrations that cannot be run in a transaction unless you added some annotation. If you added annotation I suppose it could split the migration plan into contiguous migrations that can be transactional and ones that can't. Sounds pretty complicated.

One advantage to have transaction granularity to the individual migration level is that if something goes wrong in a transaction, you still keep the previous ones that ran before it as those are committed. If you have a bunch of schema changes in a row that need to be transactional with eachother, couldn't you just concatenate them into one query? I guess the API isn't quite so nice there because that forces you to to have one description and name for things that may be totally different.

**Comment by 3noch** [comment]
@MichaelXavier I actually think you would _not_ want some of the migrations to remain committed if later ones failed. If your database is at state A and your service needs it to be at state D, then leaving it at state C means that neither the old version of your app, nor the new one can run. Now you can't even rollback to the previous service!

**Comment by 3noch** [comment]
When I wrap the migration with `withTransaction` I get a warning that we're already in a transaction. Not sure why.

**Comment by 3noch** [comment]
Silly me: you already do run everything within a transaction in `runMigrations`.

**Comment by 3noch** [comment]
Feel free to close this.
